name: Validate Codeowners
on:
  workflow_dispatch:

  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: "Checkout source code at current commit"
      uses: actions/checkout@v4
    - uses: mszostok/codeowners-validator@v0.7.1
      if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
      name: "Full check of CODEOWNERS"
      with:
        checks: "syntax,duppatterns"
        github_access_token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: mszostok/codeowners-validator@v0.7.1
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
      name: "Syntax check of CODEOWNERS"
      with:
        checks: "syntax,duppatterns"
